version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db  # 서비스 이름과 일치시킴
      - DB_PORT=3306
      - DB_NAME=mydatabase
      - DB_USER=root  # DB와 일치시키도록 root로 변경
      - DB_PASSWORD=root_password
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8000
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: db  # 컨테이너 이름을 서비스 이름과 일치시킴
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root  # root로 변경
      MYSQL_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
