services:
  # mysql:
  #   build:
  #     context: ./db
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   networks:
  #     - app-network
  #   # db 폴더를 context로 설정

  #   restart: always

  backend:
    build:
      # backend 폴더를 context로 설정
      context: ./test
      dockerfile: Dockerfile  # test 폴더 내 Dockerfile.backend
    ports:
      - "8000:8080"
    networks:
      - app-network
    restart: on_failure

  frontend:
    build:
      # frontend 폴더를 context로 설정
      context: ./vite-project
      dockerfile: Dockerfile  # vite-project 폴더 내 Dockerfile.frontend
    environment:
      - BACKEND_HOST=backend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: on_failure

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
